### ISSUE TITLE
Add better image in the home page

### ISSUE THREAD

**Issue by joyceg** [joyceg/drupalCamp17#8]
Think of something like Drupla swags, goodies.
Refer twitter too.

**Comment by Chiranjeeb2410** [comment]
![drupal amrita](https://cloud.githubusercontent.com/assets/20497155/21317392/eddfab60-c5d2-11e6-8c6f-79fd62548a0c.jpg)

**Comment by Chiranjeeb2410** [comment]
This should do I think (#25). Kindly close the issue if fixed.

**Comment by joyceg** [comment]
https://github.com/joyceg/drupalCamp17/pull/25
