### ISSUE TITLE
Update social links 

### ISSUE THREAD

**Issue by joyceg** [joyceg/drupalCamp17#9]
Update social links in the top of the website with necessary links.

**Comment by abhilal007** [comment]
can you give the necessary links.

**Comment by joyceg** [comment]
grep here: http://foss.amrita.ac.in/

**Comment by abhilal007** [comment]
its done ( https://github.com/joyceg/drupalCamp17/pull/10 )

**Comment by joyceg** [comment]
https://github.com/joyceg/drupalCamp17/pull/10
